sdk/src/main/java/io/opentdf/platform/sdk/SDK.java, sdk/src/main/java/io/opentdf/platform/sdk/SDKBuilder.java
It was easy to overlook the difference between how KAS channels and channels used to communicate with the platform
were made. This puts the creation code in the same place.
=> fix: get rid of duplicate channel logic

README.md, pom.xml, sdk/pom.xml, sdk/src/main/java/io/opentdf/platform/sdk/GRPCAuthInterceptor.java, sdk/src/main/java/io/opentdf/platform/sdk/SDKBuilder.java, sdk/src/test/java/io/opentdf/platform/sdk/SDKBuilderTest.java
- Issue #57 - Add kickstart SSLFactory to allow the configuration of a custom truststore for communications.
=> feat(sdk): add ssl context

sdk/src/main/java/io/opentdf/platform/sdk/SDK.java
Expose SDK for downstream use.
=> feat(sdk): Issue #60 - expose SDK

sdk/src/main/java/io/opentdf/platform/sdk/TDF.java, sdk/src/main/java/io/opentdf/platform/sdk/TDFWriter.java, sdk/src/main/java/io/opentdf/platform/sdk/ZipWriter.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFE2ETest.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFTest.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFWriterTest.java, sdk/src/test/java/io/opentdf/platform/sdk/ZipReaderTest.java, sdk/src/test/java/io/opentdf/platform/sdk/ZipWriterTest.java
The previous API was logically incorrect and the only reason that we hadn't uncovered it was because we
only had payloads that had one segment.
Previously we'd write a manifest entry for each segment. Now we return a stream that clients can write into
for the payload. So the API changes to
```java
var writer = new ZipWriter(out);
writer.data("entry one", new byte[] { ... });
try (var out = writer.stream("entry two")) {
var fi = new FileInputStream("...");
fi.transferTo(out);
}
writer.finish(); // write the zip manifest
```
Also change things so that we can handle streams that don't return all of the bytes requested during
a given read. Previously we assumed that a read would always return all of the bytes that might be available
in a stream.
Address …
=> fix: create TDFs larger than a single segment

sdk/src/main/java/io/opentdf/platform/sdk/nanotdf/ECKeyPair.java
Force the correct use of Bouncy Castle Provider to avoid downstream non-deterministic provider usage and cross - classloader issues for some target environments.
=> fix: Force BC provider use

.github/workflows/checks.yaml
need to merge opentdf/tests PR first https://github.com/opentdf/tests/pull/153
=> feat(ci): Add xtest workflow trigger

sdk/src/main/java/io/opentdf/platform/sdk/nanotdf/ResourceLocator.java
This is prep for the incoming changes related to ADR below.
Updated the constructor to mask the first byte with 0xF, ensuring only the first four bits are used for indexing the protocol. This prevents potential out-of-bounds errors when retrieving values from the NanoTDFType.Protocol enum.
Issue: https://github.com/opentdf/platform/issues/1203
Specification: https://github.com/opentdf/spec/pull/40
ADR: https://github.com/opentdf/platform/issues/900
=> feat(core): NanoTDF resource locator protocol bit mask

sdk/src/main/java/io/opentdf/platform/sdk/Config.java, sdk/src/main/java/io/opentdf/platform/sdk/TDF.java, sdk/src/test/java/io/opentdf/platform/sdk/ConfigTest.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFTest.java
- Add withMimeType TDF Config option, which will in-turn add it to the Manifest.Payload.MimeType
- Add getManifest() function to the reader object. In-sync with Golang SDK.
=> feat(sdk): add mime type.

sdk/src/main/java/io/opentdf/platform/sdk/SDKBuilder.java, sdk/src/test/java/io/opentdf/platform/sdk/SDKBuilderTest.java
fix for #115 
Note, to repro the error run the new test _testPlatformPlainTextAndIDPWithSSL_ without the fix in SDKBuilder.
=> fix: Issue #115 - fix for SSL Context for IDP and plaintext platform

sdk/src/main/java/io/opentdf/platform/sdk/AsymEncryption.java, sdk/src/test/java/io/opentdf/platform/sdk/AsymEncryptionTest.java
We support certs in the go sdk, we should have the same support here
=> fix(core): Add support for certs

.github/workflows/checks.yaml, cmdline/src/main/java/io/opentdf/platform/Command.java
Currently --insecure forces http plaintext. Instead have --insecure use an ssl factory that does not check certs. Also add a flag for http plaintext (-h).
=> feat(cli): Add insecure option for https connections

cmdline/src/main/java/io/opentdf/platform/Command.java
- Allow `cmdlint.jar help encryptnano` to give explanation of subcommand
- Adds `--ecdsa-binding` boolean option to `encryptnano` subcommand
=> feat(cmdline): Adds --ecdsa-binding and help

.github/workflows/release.yaml
Revised the GPG key and Maven credentials used in the GitHub release workflow for better security and consistency. The `gpg-private-key` and `gpg-passphrase` are now using updated secret variables. Updated the Maven credentials to use consistent naming conventions across the workflow.
=> fix: GPG key and Maven credentials in release workflow

pom.xml
The `<modules>` section was removed from the `pom.xml` file to streamline project configuration; it is defined in profile for each.
The snapshot repository was enabled under the GitHub Packages repository configuration. This ensures better management of snapshot and release artifacts.
=> fix: GitHub packages snapshot repo

pom.xml
Update maven-deploy-plugin to be used during `stage` for deployment to GitHub Packages, this plugin is excluded from `release` to Maven Central
Replaced maven-deploy-plugin version 3.1.1 with 3.1.2 and added configuration for GitHub package repository. Restored lifecycle exclusion for default-deploy phase ensuring no impact on the build process.
=> chore: fix to deploy to GitHub Packages

.github/workflows/release.yaml
Update GitHub credentials source in release workflow for `stage` profile
Changed the Maven settings to use environment variables instead of secrets for GitHub credentials. This enhances security by aligning with the recommended best practices for GitHub Actions.
=> chore: env.GITHUB_ACTOR

.github/workflows/release.yaml
Refactored the Maven setup process to avoid redundant creation of `settings.xml`. This uses the configuration options provided directly within the `setup-java` action. This change reduces duplication and simplifies the workflow for both GitHub Packages and Maven Central publishing.
=> chore: settings.xml from actions/setup-java

README.md
minor edits to wording and structure
=> docs: minor Java SDK README updates

.github/workflows/checks.yaml, pom.xml, sdk/pom.xml
Introduce a new Maven profile for JaCoCo test coverage reporting in the `pom.xml`. Additionally, update the GitHub Actions workflow to include a SonarCloud scan that uses the JaCoCo coverage data.
DSP-119
DSP-120
=> ci: SonarCloud coverage

sdk/src/main/java/io/opentdf/platform/sdk/AesGcm.java, sdk/src/main/java/io/opentdf/platform/sdk/AssertionConfig.java, sdk/src/main/java/io/opentdf/platform/sdk/AsymDecryption.java, sdk/src/main/java/io/opentdf/platform/sdk/AsymEncryption.java, sdk/src/main/java/io/opentdf/platform/sdk/AutoConfigureException.java, sdk/src/main/java/io/opentdf/platform/sdk/Autoconfigure.java, sdk/src/main/java/io/opentdf/platform/sdk/Config.java, sdk/src/main/java/io/opentdf/platform/sdk/CryptoUtils.java, sdk/src/main/java/io/opentdf/platform/sdk/InvalidZipException.java, sdk/src/main/java/io/opentdf/platform/sdk/KASClient.java, sdk/src/main/java/io/opentdf/platform/sdk/KASKeyCache.java, sdk/src/main/java/io/opentdf/platform/sdk/Manifest.java, sdk/src/main/java/io/opentdf/platform/sdk/NanoTDF.java, sdk/src/main/java/io/opentdf/platform/sdk/PolicyObject.java, sdk/src/main/java/io/opentdf/platform/sdk/SDK.java, sdk/src/main/java/io/opentdf/platform/sdk/SDKBuilder.java, sdk/src/main/java/io/opentdf/platform/sdk/SDKException.java, sdk/src/main/java/io/opentdf/platform/sdk/TDF.java, sdk/src/main/java/io/opentdf/platform/sdk/TDFReader.java, sdk/src/main/java/io/opentdf/platform/sdk/TDFWriter.java, sdk/src/main/java/io/opentdf/platform/sdk/ZipReader.java, sdk/src/main/java/io/opentdf/platform/sdk/ZipWriter.java, sdk/src/main/java/io/opentdf/platform/sdk/package-info.java
Added JavaDoc comments to multiple classes and methods across the SDK, providing detailed descriptions of their functionality and usage. This enhances the readability and maintainability of the code.
DSP-119
=> docs: JavaDoc

.github/workflows/checks.yaml, sdk/pom.xml
Configured the Jacoco plugin to specify the output directory for report generation. This change ensures that the report is consistently placed in the target directory for easier access and management.
=> ci: coverage report fix

sdk/src/main/java/io/opentdf/platform/sdk/NanoTDF.java
This change is motivated from the CodeQL result: https://github.com/opentdf/java-sdk/security/code-scanning/1
Although that use of a static IV is deliberate, it helped highlight that we should ensure that there is no reuse of the IV when encrypting the data.
In addition it was found that there were two places the key was logged, due to the sensitivity of the key this has been removed.
=> fix: NanoTDF secure key from debug logging and iv conflict risk

sdk/src/main/java/io/opentdf/platform/sdk/NanoTDF.java
ByteBuffer could have an array offset. We consider the length of the ByteBuffer, but we do not consider the offset and default it to 0. This PR fixes this problem by adding in the array offset when encrypting.
=> fix(sdk): uses offset for ByteBuffer array offset

examples/src/main/java/io/opentdf/platform/DecryptCollectionExample.java, examples/src/main/java/io/opentdf/platform/EncryptCollectionExample.java, sdk/src/main/java/io/opentdf/platform/sdk/Config.java, sdk/src/main/java/io/opentdf/platform/sdk/NanoTDF.java, sdk/src/main/java/io/opentdf/platform/sdk/nanotdf/CollectionStore.java, sdk/src/main/java/io/opentdf/platform/sdk/nanotdf/CollectionStoreImpl.java, sdk/src/test/java/io/opentdf/platform/sdk/NanoTDFTest.java
Adds Collection API to NanoTDF. 
Decrypt: NanoTDF Client constructor will have a option to enable `CollectionStore` or pass in a custom `CollectionStore` implementation.
Encrypt: NanoTDFConfig will have an option `WithCollection` to enable writing as a Collection rather as individual NanoTDF's. 
Examples for Collection are made in `ExampleEncryptCollection` and `ExampleDecryptCollection` and will successfully encrypt/decrypt with default OpenTDF Platform Fixtures. ExampleDecryptCollection will have only 1 Unwrap Request to Platform.
=> feat(sdk): adds Collections API

.github/workflows/checks.yaml, cmdline/src/main/java/io/opentdf/platform/Command.java, sdk/src/main/java/io/opentdf/platform/sdk/AssertionConfig.java, sdk/src/main/java/io/opentdf/platform/sdk/TDF.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFTest.java
Adding wither-assertion-verification-keys to the cli, support for pasing in signing key pems in the assertions json string
=> feat: Add assertion verification

sdk/src/main/java/io/opentdf/platform/sdk/Autoconfigure.java, sdk/src/main/java/io/opentdf/platform/sdk/TDF.java
Covered by [a new xtest](https://github.com/opentdf/tests/pull/240)
=> fix(sdk): group splits with empty/missing split IDs together

cmdline/src/main/java/io/opentdf/platform/Command.java, sdk/src/main/java/io/opentdf/platform/sdk/Manifest.java, sdk/src/main/java/io/opentdf/platform/sdk/TDF.java, sdk/src/test/java/io/opentdf/platform/sdk/ManifestTest.java, sdk/src/test/java/io/opentdf/platform/sdk/ZipReaderTest.java, sdk/src/test/resources/io.opentdf.platform.sdk.TestData/manifest-with-object-statement-value.json
Some SDKs don't set assertion values as objects instead of strings so we set them to string values when we deserialize
Also:
* encapsulate the `gson` instance that we use for `Manifest` deserialization so that we don't have to 
keep setting the options in different places
* remove the `ManifestDeserializer` since its purpose is to make the `assertions` list non-null but since
we have encapsulated the deserialization we can set it there
* add a setting to ignore assertions in the `cmdline` app so that we can do so in xtests
=> fix(sdk): deserialize object statement values correctly

examples/pom.xml, examples/src/main/java/io/opentdf/platform/DecryptExample.java, examples/src/main/java/io/opentdf/platform/EncryptExample.java, sdk/src/main/java/io/opentdf/platform/sdk/Config.java, sdk/src/main/java/io/opentdf/platform/sdk/CryptoUtils.java, sdk/src/main/java/io/opentdf/platform/sdk/KASClient.java, sdk/src/main/java/io/opentdf/platform/sdk/KeyType.java, sdk/src/main/java/io/opentdf/platform/sdk/Manifest.java, sdk/src/main/java/io/opentdf/platform/sdk/SDK.java, sdk/src/main/java/io/opentdf/platform/sdk/TDF.java, sdk/src/main/java/io/opentdf/platform/sdk/nanotdf/ECKeyPair.java, sdk/src/test/java/io/opentdf/platform/sdk/KASClientTest.java, sdk/src/test/java/io/opentdf/platform/sdk/NanoTDFTest.java, sdk/src/test/java/io/opentdf/platform/sdk/SDKBuilderTest.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFE2ETest.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFTest.java
- Adds a new `ec-wrapped` KAO type that uses a hybrid EC encryption scheme to wrap the values
- To use with SDK, adds a new `WithWrappingKeyAlg` and `WithSessionKeyType` functional option
=> feat(sdk):  EC-wrapped key support for ZTDF

CODEOWNERS
This PR updates CODEOWNERS to include @opentdf/security for files:
* examples/pom.xml
* pom.xml
* cmdline/pom.xml
* sdk/pom.xml
=> chore:  Update CODEOWNERS to include @opentdf/security for helping with Dependabot

cmdline/src/main/java/io/opentdf/platform/Command.java, release-please.json
- Fixes error in version information with `--version` flag
- Lets release-please properly update the version info
=> fix(sdk): Update version information

.github/workflows/checks.yaml, .github/workflows/update-platform-branch.yaml
Adds a dependabot-style workflow, `update-platform-branch`, which will bump the protocol buffer source tag, used during the generate-sources build phase for RPCs with the policy and key access services.
It runs on a schedule to create a dependabot/rennovate style PR,  but if you need to bump faster it supports manual dispatch, or, if we get it setup, repository dispatch to make it slightly more automated
=> chore(ci): Adds workflow to bump protocol buffers

.github/workflows/checks.yaml, README.md, cmdline/src/main/java/io/opentdf/platform/Command.java, examples/src/main/java/io/opentdf/platform/DecryptCollectionExample.java, examples/src/main/java/io/opentdf/platform/DecryptExample.java, sdk/src/main/java/io/opentdf/platform/sdk/Config.java, sdk/src/main/java/io/opentdf/platform/sdk/KASClient.java, sdk/src/main/java/io/opentdf/platform/sdk/NanoTDF.java, sdk/src/main/java/io/opentdf/platform/sdk/SDK.java, sdk/src/main/java/io/opentdf/platform/sdk/SDKBuilder.java, sdk/src/main/java/io/opentdf/platform/sdk/TDF.java, sdk/src/test/java/io/opentdf/platform/sdk/Fuzzing.java, sdk/src/test/java/io/opentdf/platform/sdk/NanoTDFTest.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFE2ETest.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFTest.java
Adds an allowlist for kas urls
=> feat(sdk): KAS Allowlist

sdk/src/main/java/io/opentdf/platform/sdk/ECCMode.java, sdk/src/main/java/io/opentdf/platform/sdk/ECKeyPair.java, sdk/src/main/java/io/opentdf/platform/sdk/Header.java, sdk/src/main/java/io/opentdf/platform/sdk/KASClient.java, sdk/src/main/java/io/opentdf/platform/sdk/KeyType.java, sdk/src/main/java/io/opentdf/platform/sdk/NanoTDF.java, sdk/src/main/java/io/opentdf/platform/sdk/NanoTDFType.java, sdk/src/main/java/io/opentdf/platform/sdk/PolicyInfo.java, sdk/src/main/java/io/opentdf/platform/sdk/SymmetricAndPayloadConfig.java, sdk/src/main/java/io/opentdf/platform/sdk/TDF.java, sdk/src/test/java/io/opentdf/platform/sdk/ECKeyPairTest.java, sdk/src/test/java/io/opentdf/platform/sdk/HeaderTest.java, sdk/src/test/java/io/opentdf/platform/sdk/NanoTDFHeaderTest.java, sdk/src/test/java/io/opentdf/platform/sdk/NanoTDFTest.java, sdk/src/test/java/io/opentdf/platform/sdk/TDFTest.java
Instead of taking what's in the config use what's in the key since it's actually what has been used
to actually do the cryptography. Also some refactoring to simplify how we get key metadata.
One thing that I noticed during was that `compressedPublicKeySize` is less than `keySize`. I'm not
sure if this is correct but if it is I'd like to find out so I can comment why that's the case.
=> feat(sdk): Get the algorithm from the KASInfo and not the config

sdk/pom.xml
In gateway we are seeing an error like
```
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length
```
when fetching attributes. [`v2.6.2` of platform contains `v0.5.0` of `protocol/go`](https://github.com/virtru-corp/data-security-platform/blob/v2.6.2/go.mod#L34) and there are changes between the two versions in the attributes. This should at least be safe.
=> fix(sdk): upgrade the platform protocol code
